### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object. in latest nuget

### ISSUE THREAD

**Issue by pksorensen** [unitycontainer/microsoft-dependency-injection#12]
```
            var c = new UnityContainer();
            var spf = new ServiceProviderFactory(c);
            var cc = spf.CreateBuilder(new ServiceCollection());
```

throws the following exceptions

```
Test Name:	ShouldUseDefaultValue
Test FullName:	SInnovations.ServiceFabric.Unity.UnitTests.UnitTest1.ShouldUseDefaultValue
Test Source:	C:\dev\S-Innovations\S-Innovations.ServiceFabric.Unity\test\S-Innovations.ServiceFabric.Unity.UnitTests\UnitTest1.cs : line 33
Test Outcome:	Failed
Test Duration:	0:00:00.1743851

Result StackTrace:	
at Unity.Strategies.ArrayResolveStrategy.RequiredToBuildType(IUnityContainer container, INamedType namedType, InjectionMember[] injectionMembers)
   at Unity.UnityContainer.GetBuilders(InternalRegistration registration)
   at Unity.UnityContainer.CreateRegistration(Type type, String name, Type policyInterface, IBuilderPolicy policy)
   at Unity.UnityContainer.Set(Type type, String name, Type policyInterface, IBuilderPolicy policy)
   at Unity.UnityContainer.CreateAndSetPolicy(Type type, String name, Type policyInterface, IBuilderPolicy policy)
   at Unity.UnityContainer.ContainerContext.Set(Type type, String name, Type policyInterface, IBuilderPolicy policy)
   at Unity.Policy.PolicyListExtensions.SetDefault[TPolicyInterface](IPolicyList policies, TPolicyInterface policy)
   at Unity.Microsoft.DependencyInjection.MdiExtension.Initialize()
   at Unity.Extension.UnityContainerExtension.InitializeExtension(ExtensionContext context)
   at Unity.UnityContainer.AddExtension(UnityContainerExtension extension)
   at Unity.Microsoft.DependencyInjection.ServiceProviderFactory.CreateBuilder(IServiceCollection services)
   at SInnovations.ServiceFabric.Unity.UnitTests.UnitTest1.ShouldUseDefaultValue()
Result Message:	
Test method SInnovations.ServiceFabric.Unity.UnitTests.UnitTest1.ShouldUseDefaultValue threw exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
```

**Comment by ENikS** [comment]
Could you provide a test case demonstrating the error?

**Comment by pksorensen** [comment]
clone and run this: https://github.com/pksorensen/UnityIssueRepro

**Comment by ENikS** [comment]
I'd much rather prefer something like this:
```C#
        [TestMethod]
        public void TestMethod()
        {
            using (IUnityContainer provider = new UnityContainer())
            {
                // Arrange
                provider.RegisterType<IService, EmailService>();

                // Act
                var service1 = provider.Resolve<IService>();
                var service2 = provider.Resolve<IService>();

                // Assert
                Assert.IsInstanceOfType(service1, typeof(EmailService));
                Assert.IsInstanceOfType(service1, typeof(EmailService));

                Assert.AreNotSame(service1, service2);
            }

        }

```

**Comment by pksorensen** [comment]
I know and is working on that. But havent figured out why it throws the error.

The repo is a very minimalistisk aspnet core world app that shows the issue. It cant run as it throws the exception on startup.

**Comment by pksorensen** [comment]
Bassically, the example in the readme do not work

**Comment by ENikS** [comment]
I see. I'll check

**Comment by pksorensen** [comment]
I cloned the project and added this to the current test:

```
    public class Tests : DependencyInjectionSpecificationTests
    {

 


        protected override IServiceProvider CreateServiceProvider(IServiceCollection serviceCollection)
        {

            var c = new UnityContainer();
            var spf = new ServiceProviderFactory(c);

            var cc = spf.CreateBuilder(serviceCollection);

             var sp =spf.CreateServiceProvider(cc);
            return sp;
            //return serviceCollection.BuildServiceProvider();
        }

       
    }
```

then it throws on all tests more or less

**Comment by pksorensen** [comment]
Guess we need to figure out why this null comes in:

![image](https://user-images.githubusercontent.com/2718591/36937742-463b70ce-1f18-11e8-8a97-dc03c9675d4c.png)

**Comment by pksorensen** [comment]
I am ending up at 

```
public static void SetDefault<TPolicyInterface>(this IPolicyList policies, TPolicyInterface policy)
            where TPolicyInterface : IBuilderPolicy
        {
            (policies ?? throw new ArgumentNullException(nameof(policies))).Set(null, null, typeof(TPolicyInterface), policy);
        }
```

null is being set in MdiExtension
```
  internal class MdiExtension : UnityContainerExtension
    {
        protected override void Initialize()
        {
            Context.Policies.SetDefault<IConstructorSelectorPolicy>(new ConstructorSelectorPolicy());
        }

        public ILifetimeContainer Lifetime => Context.Lifetime;
    }
```

All tests could be fixed with

```
 internal IList<BuilderStrategy> GetBuilders(InternalRegistration registration)
        {
            var chain = new List<BuilderStrategy>();
            var strategies = _buildChain;

            for (var i = 0; i < strategies.Length; i++)
            {
                var strategy = strategies[i];

                if (registration.Type != null && strategy.RequiredToBuildType(this, registration, null))
                    chain.Add(strategy);
            }

            return chain;
        }
```

**Comment by pksorensen** [comment]
added a pull request. 

Just ignore it if there is a better fix - as i dont have the overview of the project as a hole.

What timeframe should i expect for a updated nuget build to roll out if accepted?

**Comment by ENikS** [comment]
Deployed

**Comment by pksorensen** [comment]
awesome, thanks also for deploying :)

**Comment by karelkral** [comment]
This bug was reintroduced in UnityContainer #94. See #97.

**Comment by ENikS** [comment]
Should be ok now, thx for reporting

**Comment by pksorensen** [comment]
thanks @ENikS :)

**Comment by pksorensen** [comment]
Upgraded nugets in my project and this started throwing:

```
System.AggregateException:
   at Unity.UnityContainer.Dispose (Unity.Container, Version=5.8.9.0, Culture=neutral, PublicKeyToken=489b6accfaf20ef0)
   at Unity.UnityContainer.Dispose (Unity.Container, Version=5.8.9.0, Culture=neutral, PublicKeyToken=489b6accfaf20ef0)
   at Unity.Microsoft.DependencyInjection.ServiceProvider.Dispose (Unity.Microsoft.DependencyInjection, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Dispose (Microsoft.AspNetCore.Hosting, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build (Microsoft.AspNetCore.Hosting, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at SInnovations.ServiceFabric.RegistrationMiddleware.AspNetCore.Services.KestrelHostingService+<>c__DisplayClass15_0.<CreateServiceInstanceListeners>b__1 (S-Innovations.ServiceFabric.RegistrationMiddleware.AspNetCore, Version=2.1.2.0, Culture=neutral, PublicKeyToken=nullS-Innovations.ServiceFabric.RegistrationMiddleware.AspNetCore, Version=2.1.2.0, Culture=neutral, PublicKeyToken=null: C:\dev\ServiceFabricGateway\src\S-Innovations.ServiceFabric.RegistrationMiddleware.AspNetCore\Services\KestrelHostingService.csS-Innovations.ServiceFabric.RegistrationMiddleware.AspNetCore, Version=2.1.2.0, Culture=neutral, PublicKeyToken=null: 265)
Inner exception System.NullReferenceException handled at Unity.UnityContainer.Dispose:
   at Microsoft.ApplicationInsights.ServiceFabric.Module.ServiceRemotingRequestTrackingTelemetryModule.Dispose (Microsoft.AI.ServiceFabric.Native, Version=2.1.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Unity.Microsoft.DependencyInjection.Lifetime.InjectionSingletonLifetimeManager.RemoveValue (Unity.Microsoft.DependencyInjection, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null)
   at Unity.Container.Lifetime.LifetimeContainer.Dispose (Unity.Container, Version=5.8.9.0, Culture=neutral, PublicKeyToken=489b6accfaf20ef0)
Inner exception System.NullReferenceException handled at Unity.UnityContainer.Dispose:
   at Microsoft.ApplicationInsights.ServiceFabric.Module.ServiceRemotingDependencyTrackingTelemetryModule.Dispose (Microsoft.AI.ServiceFabric.Native, Version=2.1.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Unity.Microsoft.DependencyInjection.Lifetime.InjectionSingletonLifetimeManager.RemoveValue (Unity.Microsoft.DependencyInjection, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null)
   at Unity.Container.Lifetime.LifetimeContainer.Dispose (Unity.Container, Version=5.8.9.0, Culture=neutral, PublicKeyToken=489b6accfaf20ef0)
Inner exception System.AggregateException handled at Unity.UnityContainer.Dispose:
   at Unity.UnityContainer.Dispose (Unity.Container, Version=5.8.9.0, Culture=neutral, PublicKeyToken=489b6accfaf20ef0)
   at Unity.UnityContainer.Dispose (Unity.Container, Version=5.8.9.0, Culture=neutral, PublicKeyToken=489b6accfaf20ef0)
   at Unity.Microsoft.DependencyInjection.Lifetime.InjectionSingletonLifetimeManager.RemoveValue (Unity.Microsoft.DependencyInjection, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null)
   at Unity.Container.Lifetime.LifetimeContainer.Dispose (Unity.Container, Version=5.8.9.0, Culture=neutral, PublicKeyToken=489b6accfaf20ef0)
Inner exception System.NullReferenceException handled at Unity.UnityContainer.Dispose:
   at Microsoft.ApplicationInsights.ServiceFabric.Module.ServiceRemotingRequestTrackingTelemetryModule.Dispose (Microsoft.AI.ServiceFabric.Native, Version=2.1.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Unity.Microsoft.DependencyInjection.Lifetime.InjectionSingletonLifetimeManager.RemoveValue (Unity.Microsoft.DependencyInjection, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null)
   at Unity.Container.Lifetime.LifetimeContainer.Dispose (Unity.Container, Version=5.8.9.0, Culture=neutral, PublicKeyToken=489b6accfaf20ef0)
Inner exception System.NullReferenceException handled at Unity.UnityContainer.Dispose:
   at Microsoft.ApplicationInsights.ServiceFabric.Module.ServiceRemotingDependencyTrackingTelemetryModule.Dispose (Microsoft.AI.ServiceFabric.Native, Version=2.1.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Unity.Microsoft.DependencyInjection.Lifetime.InjectionSingletonLifetimeManager.RemoveValue (Unity.Microsoft.DependencyInjection, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null)
   at Unity.Container.Lifetime.LifetimeContainer.Dispose (Unity.Container, Version=5.8.9.0, Culture=neutral, PublicKeyToken=489b6accfaf20ef0)
```

Guessing its related. but will start debugging now

**Comment by ENikS** [comment]
Unit test?

**Comment by pksorensen** [comment]
still trying to get my head around what is going on. but just saw

ServiceRemotingDependencyTrackingTelemetryModule

So might not be in unity the problem is

**Comment by pksorensen** [comment]
I found another unrelated issue that started to surface now.

 [TestMethod]
        public void Test1()
        {
            var container = new UnityContainer();
           
            var strings = container.Resolve<IEnumerable<string>>().ToArray();

            Assert.AreEqual(0, strings.Length);


            var filters = container.Resolve<IEnumerable< IStartupConfigureContainerFilter<IUnityContainer>>>().ToArray();

            Assert.AreEqual(0, filters.Length);

        }

```
Test Name:	Test1
Test FullName:	SInnovations.ServiceFabric.Unity.UnitTests.UnitTest1.Test1
Test Source:	C:\dev\S-Innovations.ServiceFabric.Unity\test\S-Innovations.ServiceFabric.Unity.UnitTests\UnitTest1.cs : line 305
Test Outcome:	Failed
Test Duration:	0:00:00.4228911

Result StackTrace:	
at Unity.ObjectBuilder.BuildPlan.DynamicMethod.Creation.DynamicMethodConstructorStrategy.ThrowForAttemptingToConstructInterface(IBuilderContext context)
   at lambda_method(Closure , IBuilderContext )
   at Unity.ObjectBuilder.BuildPlan.DynamicMethod.DynamicBuildPlanGenerationContext.<>c__DisplayClass16_0.<GetBuildMethod>b__0(IBuilderContext context)
   at Unity.ObjectBuilder.BuildPlan.DynamicMethod.DynamicMethodBuildPlan.BuildUp(IBuilderContext context)
   at Unity.Strategies.BuildPlanStrategy.PreBuildUp(IBuilderContext context)
   at Unity.Builder.BuilderContext.NewBuildUp(Type type, String name, Action`1 childCustomizationBlock)
   at Unity.UnityContainer.ResolveGenericRegistrations[T](IBuilderContext context, IEnumerable`1 registrations)
   at Unity.UnityContainer.ResolveGenericEnumerable[T](IBuilderContext context, Type type)
--- End of inner exception stack trace ---
    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Unity.Strategies.EnumerableResolveStrategy.<>c__DisplayClass4_1.<PreBuildUp>b__0(IBuilderContext c)
   at Unity.ObjectBuilder.BuildPlan.DynamicMethod.DynamicMethodBuildPlan.BuildUp(IBuilderContext context)
   at Unity.Strategies.EnumerableResolveStrategy.PreBuildUp(IBuilderContext context)
   at Unity.UnityContainer.ThrowingBuildUp(IBuilderContext context)
--- End of inner exception stack trace ---
    at Unity.UnityContainer.ThrowingBuildUp(IBuilderContext context)
   at Unity.UnityContainer.Resolve(Type typeToBuild, String nameToBuild, ResolverOverride[] resolverOverrides)
   at Unity.UnityContainerExtensions.Resolve[T](IUnityContainer container, ResolverOverride[] overrides)
   at SInnovations.ServiceFabric.Unity.UnitTests.UnitTest1.Test1() in C:\dev\S-Innovations.ServiceFabric.Unity\test\S-Innovations.ServiceFabric.Unity.UnitTests\UnitTest1.cs:line 316
Result Message:	
Test method SInnovations.ServiceFabric.Unity.UnitTests.UnitTest1.Test1 threw exception: 
Unity.Exceptions.ResolutionFailedException: Resolution of the dependency failed, type = 'System.Collections.Generic.IEnumerable`1[Microsoft.AspNetCore.Hosting.Internal.IStartupConfigureContainerFilter`1[Unity.IUnityContainer]]', name = '(none)'.
Exception occurred while: while resolving.
Exception is: TargetInvocationException - Exception has been thrown by the target of an invocation.
-----------------------------------------------
At the time of the exception, the container was: 
  Resolving System.Collections.Generic.IEnumerable`1[Microsoft.AspNetCore.Hosting.Internal.IStartupConfigureContainerFilter`1[Unity.IUnityContainer]],(none)
    Resolving Microsoft.AspNetCore.Hosting.Internal.IStartupConfigureContainerFilter`1[Unity.IUnityContainer],(none)
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: The current type, Microsoft.AspNetCore.Hosting.Internal.IStartupConfigureContainerFilter`1[Unity.IUnityContainer], is an interface and cannot be constructed. Are you missing a type mapping?

```

Fails with enumerable<some generic interface> from what i can see.

Thats not intended right?

**Comment by ENikS** [comment]
How do you define ``IStartupConfigureContainerFilter<IUnityContainer>>``?

**Comment by pksorensen** [comment]
its from microsoft hosting

```
#region Assembly Microsoft.AspNetCore.Hosting.Abstractions, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
// C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.hosting.abstractions\2.1.1\lib\netstandard2.0\Microsoft.AspNetCore.Hosting.Abstractions.dll
#endregion

using System;

namespace Microsoft.AspNetCore.Hosting.Internal
{
    //
    // Summary:
    //     This API supports the ASP.NET Core infrastructure and is not intended to be used
    //     directly from your code. This API may change or be removed in future releases.
    public interface IStartupConfigureContainerFilter<TContainerBuilder>
    {
        Action<TContainerBuilder> ConfigureContainer(Action<TContainerBuilder> container);
    }
}
```

**Comment by ENikS** [comment]
I can't reproduce. Can you PR me working test?

**Comment by pksorensen** [comment]
i am abit short on time today and fixed it with a custom EnumerableResolutionStrategy until i have time to get to the bottom of it. sorry

I will return with a PR when a bit of time is available.

**Comment by ENikS** [comment]
> At the time of the exception, the container was: 
  Resolving System.Collections.Generic.IEnumerable`1[Microsoft.AspNetCore.Hosting.Internal.IStartupConfigureContainerFilter`1[Unity.IUnityContainer]],(none)
    Resolving Microsoft.AspNetCore.Hosting.Internal.IStartupConfigureContainerFilter`1[Unity.IUnityContainer],(none)
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: The current type, Microsoft.AspNetCore.Hosting.Internal.IStartupConfigureContainerFilter`1[Unity.IUnityContainer], is an interface and cannot be constructed. Are you missing a type mapping?


Looks like type is not registered.

**Comment by pksorensen** [comment]
Yes, but would you not expect it to return a empty enumerable when no type is registered?

its aspnet core that tries to resolve `IEnumerable<IStartupConfigureContainerFilter<IUnityContainer>>`when it starts up and that leads to unity trying to resolve `IStartupConfigureContainerFilter<IUnityContainer>` which i guess it should not.

**Comment by ENikS** [comment]
You are right, what am I thinking :)
Fixed

**Comment by pksorensen** [comment]
awesome, thanks @ENikS

**Comment by kisira** [comment]
> You are right, what am I thinking :)
> Fixed

How was this fixed?  I am experiencing the same issue
