### ISSUE TITLE
InvalidOperationException when resolving a class with two constructors that have an array parameter

### ISSUE THREAD

**Issue by aidanfolkes** [unitycontainer/microsoft-dependency-injection#16]
Hi,
I'm having problems with resolving a class that has two constructors that take an array of an interface that has multiple registrations. It looks like ConstructorSelectorPolicy discounts both constructors because it believes neither can be built.
Here is a test to recreate the issue:
```
    internal class TestServiceCollection : List<ServiceDescriptor>, IServiceCollection
    {
    }

    public class ResolveArrayTests
    {
        public interface IService
        {
        }

        public interface IConsumer
        {
            IService[] Services { get; }
        }

        public class ServiceOne : IService
        {
        }

        public class ServiceTwo : IService
        {
        }

        public class Consumer : IConsumer
        {
            public Consumer(IService[] services) : this(services, "Test")
            {
            }

            public Consumer(IService[] services, string test)
            {
                this.Services = services;
            }

            public IService[] Services { get; }
        }

        [Fact]
        public void ArrayParameter()
        {
            // Arrange
            var container = new UnityContainer();
            container.RegisterType<IService, ServiceOne>("One");
            container.RegisterType<IService, ServiceTwo>("Two");
            container.RegisterType<IConsumer, Consumer>();

            var serviceCollection = new TestServiceCollection();
            serviceCollection.BuildServiceProvider(container);

            // Act
            var actual = container.Resolve<IConsumer>();

            // Assert
            Assert.Equal(2, actual.Services.Length);
        }
    }
```
And the exception stack trace:
```
at Unity.UnityContainer.ThrowingBuildUp(IBuilderContext context) in C:\Projects\unity\Container\src\UnityContainer.Resolution.cs:line 51
   at Unity.UnityContainer.Resolve(Type typeToBuild, String nameToBuild, ResolverOverride[] resolverOverrides) in C:\Projects\unity\Container\src\UnityContainer.Public.cs:line 32
   at Unity.UnityContainerExtensions.Resolve[T](IUnityContainer container, ResolverOverride[] overrides) in C:\Projects\unity\Abstractions\src\Utility\UnityContainerExtensions.cs:line 602
   at Unity.Microsoft.DependencyInjection.Tests.ResolveArrayTests.ArrayParameter() in C:\Projects\unity\Microsoft.DependencyInjection\tests\ResolveArrayTests.cs:line 59
----- Inner Stack Trace -----
   at Unity.Microsoft.DependencyInjection.Policy.ConstructorSelectorPolicy.Other(ConstructorInfo[] constructors, IBuilderContext context) in C:\Projects\unity\Microsoft.DependencyInjection\src\Policy\ConstructorSelectorPolicy.cs:line 137
   at Unity.Microsoft.DependencyInjection.Policy.ConstructorSelectorPolicy.FindDependencyConstructor[T](IBuilderContext context) in C:\Projects\unity\Microsoft.DependencyInjection\src\Policy\ConstructorSelectorPolicy.cs:line 47
   at Unity.Microsoft.DependencyInjection.Policy.ConstructorSelectorPolicy.SelectConstructor(IBuilderContext context, IPolicyList resolverPolicyDestination) in C:\Projects\unity\Microsoft.DependencyInjection\src\Policy\ConstructorSelectorPolicy.cs:line 28
   at Unity.ObjectBuilder.BuildPlan.DynamicMethod.Creation.DynamicMethodConstructorStrategy.CreateInstanceBuildupExpression(DynamicBuildPlanGenerationContext buildContext, IBuilderContext context) in C:\Projects\unity\Container\src\ObjectBuilder\BuildPlan\DynamicMethod\Creation\DynamicMethodConstructorStrategy.cs:line 101
   at Unity.ObjectBuilder.BuildPlan.DynamicMethod.Creation.DynamicMethodConstructorStrategy.PreBuildUp(IBuilderContext context) in C:\Projects\unity\Container\src\ObjectBuilder\BuildPlan\DynamicMethod\Creation\DynamicMethodConstructorStrategy.cs:line 64
   at Unity.Container.StrategyChain.BuildUp(IBuilderContext builderContext) in C:\Projects\unity\Container\src\Container\StrategyChain.cs:line 54
   at Unity.Policy.BuildPlanPolicyExtensions.ExecuteBuildUp(IBuildPlanPolicy policy, IBuilderContext context) in C:\Projects\unity\Abstractions\src\Policy\IBuildPlanPolicy.cs:line 35
   at Unity.ObjectBuilder.BuildPlan.DynamicMethod.DynamicMethodBuildPlanCreatorPolicy.CreatePlan(IBuilderContext context, INamedType buildKey) in C:\Projects\unity\Container\src\ObjectBuilder\BuildPlan\DynamicMethod\DynamicMethodBuildPlanCreatorPolicy.cs:line 42
   at Unity.Strategies.BuildPlanStrategy.PreBuildUp(IBuilderContext context) in C:\Projects\unity\Container\src\Strategies\BuildPlanStrategy.cs:line 39
   at Unity.UnityContainer.ThrowingBuildUp(IBuilderContext context) in C:\Projects\unity\Container\src\UnityContainer.Resolution.cs:line 40
Result Message:	
Unity.Exceptions.ResolutionFailedException : Resolution of the dependency failed, type = 'Unity.Microsoft.DependencyInjection.Tests.ResolveArrayTests+IConsumer', name = '(none)'.
Exception occurred while: while resolving.
Exception is: InvalidOperationException - Construtor não encontrado para Unity.Microsoft.DependencyInjection.Tests.ResolveArrayTests+Consumer
-----------------------------------------------
At the time of the exception, the container was: 
  Resolving Unity.Microsoft.DependencyInjection.Tests.ResolveArrayTests+Consumer,(none) (mapped from Unity.Microsoft.DependencyInjection.Tests.ResolveArrayTests+IConsumer, (none))

---- System.InvalidOperationException : Construtor não encontrado para Unity.Microsoft.DependencyInjection.Tests.ResolveArrayTests+Consumer
```
I've worked around this by removing the alternative constructor, since this check isn't performed if there is only one constuctor.
Also, when looking at ConstructorSelectorPolicy, I noticed that it's looking for constructors with the DependencyAttribute which can't target constructors. Should this maybe be InjectionConstructorAttribute?

**Comment by ENikS** [comment]
Yes, the algorithm used to determine if it could be resolved is not exhaustive. 
Making it more complicated will degrade performance and is not desired for most users. If you could come up with better approach I would be happy to accept a pull request.
