### ISSUE TITLE
 Cannot access disposed IServiceProvider, after upgrade to .NET Core 3.0

### ISSUE THREAD

**Issue by lokemoon** [unitycontainer/microsoft-dependency-injection#57]
Was trying to upgrade Web Application from the .NET Core 2.2 to 3.0, but ended with the error message as in subject, and try to narrow down the causes in new project templates, please see the code and route to trigger this possible error.

Program.cs

`public static void Main(string[] args)
{
  CreateWebHostBuilder(args).Build().Run();
}

public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
    WebHost.CreateDefaultBuilder(args)
        .UseUnityServiceProvider()
        .UseStartup<Startup>();`

Startup.cs
`public Startup(IConfiguration configuration)
{
  Configuration = configuration;
}
public void ConfigureContainer(IUnityContainer container)
{

}
public IConfiguration Configuration { get; }

// This method gets called by the runtime. Use this method to add services to the container.
public void ConfigureServices(IServiceCollection services)
{
  services.AddControllers();
}

// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
  if (env.IsDevelopment())
  {
    app.UseDeveloperExceptionPage();
  }

  app.UseHttpsRedirection();

  app.UseRouting();

  app.UseAuthorization();

  app.UseEndpoints(endpoints =>
  {
    endpoints.MapControllers();
  });
}`
Error message
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'IServiceProvider'.
   at Unity.Microsoft.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.FloatingPointTypeModelBinderProvider.GetBinder(ModelBinderProviderContext context)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ModelBinderFactory.CreateBinderCoreUncached(DefaultModelBinderProviderContext providerContext, Object token)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ModelBinderFactory.CreateBinder(ModelBinderFactoryContext context)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.GetParameterBindingInfo(IModelBinderFactory modelBinderFactory, IModelMetadataProvider modelMetadataProvider, ControllerActionDescriptor actionDescriptor, MvcOptions mvcOptions)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.CreateBinderDelegate(ParameterBinder parameterBinder, IModelBinderFactory modelBinderFactory, IModelMetadataProvider modelMetadataProvider, ControllerActionDescriptor actionDescriptor, MvcOptions mvcOptions)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvokerCache.GetCachedResult(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvokerProvider.OnProvidersExecuting(ActionInvokerProviderContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionInvokerFactory.CreateInvoker(ActionContext actionContext)
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointFactory.<>c__DisplayClass7_0.<CreateRequestDelegate>b__0(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Accept: */*
Accept-Encoding: gzip, deflate
Cache-Control: no-cache
Connection: keep-alive
Host: localhost:44330
User-Agent: PostmanRuntime/7.18.0
Postman-Token: 782b0552-cf06-4420-b8e9-21c260144ca6

It happen when invoking the valid route: /api/test/Search2/0000
Seem like a problem in ASP.NET Core 3.0, but the strange part is after remove the         .UseUnityServiceProvider() from program.cs, then the route mentioned above resume working as usual.

**Comment by chandramouleswaran** [comment]
+1 any updates on this?

**Comment by ENikS** [comment]
Compatibility with 3.0 might take a little while to implement. The amount of changes is significant and I just finished Core 2.2.

**Comment by ENikS** [comment]
Fixed in  [5.11.2](https://www.nuget.org/packages/Unity.Microsoft.DependencyInjection)
